### ISSUE TITLE
Possible?: Email link direct to square payment

### ISSUE THREAD

**Issue by bradjc** [um-cseg/chez-betty#199]
Is it possible to put a button in an email that would take a user directly to a square page that would let them pay off their balance?

**Comment by ppannuto** [comment]
Is the goal to do this within the user having to log in? We could probably
generate some uuid urls or something to facilitate this. From the stripe
API side it's pretty easy, the trick is maintaining the state on our end.

**Comment by bradjc** [comment]
That seems promising

**Comment by ppannuto** [comment]
I think a static uuid per person would probably be okay, since the only
permission is to deposit money, no real harm comes if it's leaked. At most,
you could see someone's debt, but >$5 is public any way. For users not in
debt we can offer a blind deposit (so as not to reveal balance) or a login
url. Sound good?

**Comment by ppannuto** [comment]
@bradjc See pushed branch for possible implementation.

**Comment by ppannuto** [comment]
Deadbeat emails also updated to include links -- this is probably good to go.
