### ISSUE TITLE
Discount/Tax errors in manual purchases

### ISSUE THREAD

**Issue by bradjc** [um-cseg/chez-betty#262]
If an admin enters a purchase for a user, the discount/tax is not applied correctly.

**Comment by ppannuto** [comment]
sigh... actually, it is applied correctly because we recalculate discounts and taxes server side when creating the actual purchase transaction and all purchase transactions go through this common code path whether terminal or admin-initiated: https://github.com/um-cseg/chez-betty/blob/master/chezbetty/datalayer.py#L173

Our protection from possible client-side corrupt values actually saved us from ourselves. The only issue the UI in the admin interface doesn't show discounts or taxes being applied.

**Comment by bradjc** [comment]
Ok great then no issue. If everything is working there is no need to manually enter purchases.
